#!/bin/bash

# Fetches PR patches from either github or bitbucket

if [ "$#" -ne 2 ]; then
        echo "usage: $0 <pr_id> <new_branch_name>"
        exit 1
fi

echo "Try fetching $1 from github"
git fetch origin pull/$1/head:$2 && exit 0

echo "Try fetching $1 from stash"
git fetch origin refs/pull-requests/$1/from:$2
